# Generated by Django 3.2 on 2021-06-26 23:07

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to=contracts.models.contract_image_directory_path)),
                ('short_description', models.CharField(blank=True, max_length=140)),
                ('public_key', models.CharField(blank=True, max_length=140)),
                ('sector', models.IntegerField(choices=[(0, 'Education'), (1, 'Sustainability'), (2, 'Healthservices')], default=None, null=True)),
            ],
        ),
    ]
