# Generated by Django 3.2 on 2021-06-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_smartcontract_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='public_key',
            new_name='hash',
        ),
    ]
