# Generated by Django 3.2 on 2021-06-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rename_public_key_smartcontract_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='sector',
            field=models.IntegerField(choices=[(0, 'Nopoverty'), (1, 'Zerohunger'), (2, 'Goodhealth'), (3, 'Qualityeducation'), (4, 'Genderequality'), (5, 'Cleanwater'), (6, 'Affordableenergy'), (7, 'Decentwork'), (8, 'Industryinnovation'), (9, 'Reduceinequality'), (10, 'Sustainablecities'), (11, 'Responsibleconsumption'), (12, 'Climateaction'), (13, 'Belowwater'), (14, 'Onland'), (15, 'Peacefulinstituions'), (16, 'Partnership')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='short_description',
            field=models.TextField(),
        ),
    ]
