# Generated by Django 3.2 on 2021-06-27 02:46

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20210627_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='hash',
            field=models.CharField(blank=True, default='KT1Puc9St8wdNoGtLiD2WXaHbWU7styaxYhD', max_length=140),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='poster',
            field=models.ImageField(blank=True, upload_to=contracts.models.contract_image_directory_path),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='sector',
            field=models.IntegerField(choices=[(0, 'Nopoverty'), (1, 'Zerohunger'), (2, 'Goodhealth'), (3, 'Qualityeducation'), (4, 'Genderequality'), (5, 'Cleanwater'), (6, 'Affordableenergy'), (7, 'Decentwork'), (8, 'Industryinnovation'), (9, 'Reduceinequality'), (10, 'Sustainablecities'), (11, 'Responsibleconsumption'), (12, 'Climateaction'), (13, 'Belowwater'), (14, 'Onland'), (15, 'Peacefulinstituions'), (16, 'Partnership')], default=15),
        ),
    ]
